version: "3.9"

services:
  web:
    build: .
    image: ${ECR_REGISTRY}/pixel_perfect:latest
    entrypoint: ["/bin/sh", "-c"]
    environment:
      - SECRET_KEY
      - EMAIL
      - EMAIL_PASSWORD
      - CLIENT_ID
      - PROJECT_ID
      - AUTH_URI
      - TOKEN_URI
      - AUTH_PROVIDER_X509_CERT_URL
      - CLIENT_SECRET
      - ECR_REGISTRY
      - ALLOWED_HOST_1
    depends_on:
      - redis
    command:
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:80
    volumes:
      - ./media:/app/media
    ports:
      - "80:80"

  queue:
    build: .
    image: ${ECR_REGISTRY}/pixel_perfect:latest
    environment:
      - DJANGO_SETTINGS_MODULE=pixel_perfect.settings
      - SECRET_KEY
      - EMAIL
      - EMAIL_PASSWORD
      - CLIENT_ID
      - PROJECT_ID
      - AUTH_URI
      - TOKEN_URI
      - AUTH_PROVIDER_X509_CERT_URL
      - CLIENT_SECRET
      - ECR_REGISTRY
      - ALLOWED_HOST_1
    depends_on:
      - web
      - redis
    entrypoint: python3 -m celery -A images.celery_tasks:celery_obj worker -l INFO
    volumes:
      - ./media:/app/media

  redis:
    image: redis:7-alpine

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"