# Generated by Django 4.2.3 on 2023-07-25 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancedimage',
            name='img_path',
            field=models.ImageField(upload_to='original_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='uploadedimages',
            name='img_path',
            field=models.ImageField(upload_to='original_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'bmp'])]),
        ),
    ]
