# Generated by Django 4.2.3 on 2023-07-26 19:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_alter_enhancedimage_img_path_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnhancedImage',
            new_name='EnhancedImages',
        ),
        migrations.DeleteModel(
            name='UploadedImages',
        ),
    ]
