# Generated by Django 4.2.3 on 2023-08-01 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0003_rename_enhancedimage_enhancedimages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancedimages",
            name="img_path",
            field=models.ImageField(
                null=True,
                upload_to="",
                validators=[django.core.validators.FileExtensionValidator(["jpg", "jpeg", "png", "bmp"])],
            ),
        ),
    ]
