name: CI

on:

  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:      
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: pip install -r pixel_perfect/requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run Django tests
        run: python manage.py test